name: Ruby CI with Minitest

on:
  push:
    branches: ["main"]
    paths:
      - "ruby/**"
      - ".github/**"
  pull_request:
    branches: ["main"]
    paths:
      - "ruby/**"
      - ".github/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1", "3.2"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          working-directory: ruby

      - name: Install dependencies
        run: |
          cd ruby
          bundle install

      - name: Run standard tests
        run: |
          cd ruby
          ruby bingo_board_test.rb

      - name: Run BDD tests
        run: |
          cd ruby
          ruby bingo_board_bdd_test.rb
